name: "Helm Operations"
run-name: "Helm for ${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }} by @${{ github.actor }}: ${{ github.event.commits[0].message }}"

on:
  push:
    branches:
    - main
    paths:
    - 'charts/**'
    - '.github/workflows/helm.yaml'
  workflow_dispatch:

jobs:
  helm-upload:
    runs-on: helm

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        fetch-tags: true

    - name: Helm lint
      id: helm-lint
      shell: bash
      run: |
        helm lint charts/*/

    - name: Get new version name
      id: version
      uses: comet-ml/gha-tools/get-new-tag@1.0.1
      with:
        do-checkout: false

    - name: Create git tag 
      run: |
        git tag ${{ steps.version.outputs.tag }}
        git push origin ${{ steps.version.outputs.tag }}

    - name: Package and upload to Dev Helm repo
      uses: comet-ml/gha-tools/release/helm@1.0.1
      with:
        aws-region: us-east-1
        aws-role-to-assume: ${{ vars.DEV_ACTION_RUNNER_ROLE_ARN }}
        aws-role-session-name: ${{ vars.ROLE_SESSION_NAME }}
        helm-registry: s3://${{ vars.DEV_REPOSITORY_BUCKET }}/charts
        charts-path: charts
        chart-name: namespace-admission
        chart-version: ${{ steps.version.outputs.tag }}
        helm-push-extra: --force --relative
