---
name: build comet namespace-admission
run-name: Build comet namespace-admission ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    tags:
    - "v?[0-9]*.[0-9]*.[0-9]*"
  # schedule:
  # - cron: "55 5 * * *"
  workflow_dispatch:
  # pull_request:
  #   branches:
  #   - main
jobs:
  build-and-upload:
    runs-on: summerwind
    steps:
    -
      name: Setup buildx
      uses: docker/setup-buildx-action@v3
    -
      name: get version
      id: version
      uses: comet-ml/gha-tools/get-new-tag@main
    -
      name: Build
      uses: docker/build-push-action@v5
      with:
        push: true
        provenance: false
        tags: ${{ vars.REGISTRY }}/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name == 'main' && 'latest' || steps.version.outputs.tag }}
        build-args: |
          gh_token=${{ secrets.GH_TOKEN }}
          DOCKER_REGISTRY=${{ vars.REGISTRY }}
          TEMPLATE_TAG=${{ vars.TEMPLATE_TAG }}
